<?php

namespace GameBundle\Repository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllGameBy($user)
    {
        $query = $this->createQueryBuilder('g')
            ->join('g.users','u')
            ->where('u.id = :user')
            ->setParameter('user', $user)
            ->getQuery();

         return $query->getResult();
    }
}
