services:
    admin.game:
        class: AdminBundle\Admin\GameAdmin
        arguments: [~, GameBundle\Entity\Game, ~]
        tags:
        - { name: sonata.admin, manager_type: orm, label: Match, group: "Match", on_top: true, icon: '<i class="fa fa-users"></i>' }
    admin.user:
        class: AdminBundle\Admin\UserAdmin
        arguments: [~, UserBundle\Entity\User, ~]
        tags:
        - { name: sonata.admin, manager_type: orm, label: Utilisateur, group: "Utilisateur", on_top: true, icon: '<i class="fa fa-users"></i>' }
    admin.level:
        class: AdminBundle\Admin\LevelAdmin
        arguments: [~, LevelBundle\Entity\Level, ~]
        tags:
        - { name: sonata.admin, manager_type: orm, label: Niveau, group: "Niveau", on_top: true, icon: '<i class="fa fa-users"></i>' }
    admin.regularityPlayers:
        class: AdminBundle\Admin\RegularityPlayerAdmin
        arguments: [~, RegularityPlayerBundle\Entity\RegularityPlayer, ~]
        tags:
        - { name: sonata.admin, manager_type: orm, label: Régularité du joueur, group: "Régularité du joueur", on_top: true, icon: '<i class="fa fa-users"></i>' }

