<?php

namespace LevelBundle\Repository;

use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * RankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRankBy($match)
    {
        $query = $this->createQueryBuilder('r')
            ->where('r.countMatch <= :match')
            ->setParameter('match', $match)
            ->orderBy('r.countMatch','DESC')
            ->setMaxResults(1)
            ->setFirstResult(0)
            ->getQuery();

        try {
            return $query->getSingleResult();
        } catch (NoResultException $e) {
        } catch (NonUniqueResultException $e) {
        }
    }
}
