<?php

namespace RegularityPlayerBundle\Repository;

/**
 * RegularityPlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegularityPlayerRepository extends \Doctrine\ORM\EntityRepository
{
}
